apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillupjava
  labels:
    app: skillupjava
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: skillupjava
  template:
    metadata:
      labels:
        app: skillupjava
    spec:
      containers:
      - name: skillupjava-container
        image: rushikesh8788/skillupjava:1  # Replace with your Docker image, updated by Jenkins pipeline
        ports:
        - containerPort: 8786  # Port exposed by your container
---
apiVersion: v1
kind: Service
metadata:
  name: skillupjava-service
spec:
  selector:
    app: skillupjava  # Selects pods with the label 'app: skillupjava'
  ports:
    - protocol: TCP
      port: 80         # Port exposed on the service
      targetPort: 8786  # Port on the container to which traffic is forwarded
      nodePort: 30008   # Port exposed on the nodes (NodePort)
  type: NodePort        # Exposes the service as a NodePort
